# Generated by Django 5.2.9 on 2025-12-08 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='about',
            field=models.TextField(blank=True, help_text='Detailed about/background section'),
        ),
        migrations.AlterField(
            model_name='person',
            name='bio',
            field=models.TextField(blank=True, help_text='Short bio or tagline'),
        ),
    ]
